### ISSUE TITLE
Host site at gitlab

### ISSUE THREAD

**Issue by sachin-gupta** [sachin-gupta/sachin-gupta.github.io#30]

**Comment by sangupta** [comment]
You cannot host site on gitlab. Gitlab does not provide public hosting on gitlab site - only enterprise installs have this facility but then you need to host your own gitlab installation.

**Comment by sangupta** [comment]
Marking it closed.

**Comment by sachin-gupta** [comment]
please be updated gitlab provides free hosting and better than GitHub see https://sagupta.gitlab.com/home. Links won't work as this is partially set.⁣

**Comment by sangupta** [comment]
The URL mentioned above does not work.

**Comment by sangupta** [comment]
Even the features link says it will work only in Gitlab EE - https://about.gitlab.com/2016/04/04/gitlab-pages-get-started/
